### ISSUE TITLE
Some new bugs in the version v.1.1.1

### ISSUE THREAD

**Issue by clccc** [ShiftLeftSecurity/joern#336]
The test version is v1.1.1. 
1. In the older Joern v1.0.186, the query commands used below is right.
![image](https://user-images.githubusercontent.com/12693134/92185233-ed72b480-ee85-11ea-9cd0-c1a14c95e70c.png)

2. The autocomplete is not functioning properly.  
![image](https://user-images.githubusercontent.com/12693134/92185509-ba7cf080-ee86-11ea-9702-21b2873f0596.png)

**Comment by clccc** [comment]
3. In theDDG, I can see a VARIABLE labed the REACHING_DEF, but I cannot get it from cpg.
![image](https://user-images.githubusercontent.com/12693134/92193851-ebb3eb80-ee9b-11ea-8028-019caccbbcbd.png)

**Comment by mpollmeier** [comment]
The release went out before the documentation update, sorry about that!
Re 1: there have been some changes in the query DSL, more detailed update is coming, but until then: 
the semantics for the `filter` and `where` steps are swapped, i.e. `cpg.method.filter(_.id == 1).l` will get you there. Or the equivalent `cpg.method.id(1).l`

2) Yes I noticed already, and I think I know what may have caused this. 

3) What you're showing here is that the "REACHING_DEF" edge does not have the "VARIABLE" property defined, but I think that's intentional because (at least in this case) it's meant to be defined on the identifier, i.e. you do need to go to the `outV` as in the first statement.

**Comment by fabsx00** [comment]
@mpollmeier he's right, `VARIABLE` is an edge property on `REACHING_DEF` edges.

**Comment by fabsx00** [comment]
I've reverted until these problems are figured out.

**Comment by mpollmeier** [comment]
This time autocompletion works: https://github.com/ShiftLeftSecurity/joern/issues/336
@fabsx00 is probably in the best position to address the REACHING_DEF.VARIABLE issue

**Comment by mpollmeier** [comment]
1) and 2) are both fixed in release v1.1.4, I can't comment on 3)

As announced in the gitter channel, please make sure you read the upgrade guide https://docs.joern.io/upgrade-guides#111-overflowdb-traversals

**Comment by clccc** [comment]
Thank you! I have other work to do recently, and I will probably  test it in this weekend.

**Comment by clccc** [comment]
In my test:
1.` cpg.id ` is still error
3. It is still exist. Some reaching-def edges do not have valid variable. 
![image](https://user-images.githubusercontent.com/12693134/92549266-6f4e4d80-f28b-11ea-8c61-b6244ffd1c0d.png)

**Comment by mpollmeier** [comment]
re 1) note that `cpg.id` is not a valid starter step: depending on what you want to do, you can either provide one or multiple ids to start with:
```
cpg.id(42L)
cpg.id(List(12L, 13L))
```
or you can start with *all* nodes and lookup or filter by their id:
```
cpg.all.id
cpg.all.id(42L)
cpg.call.id(42)
```

re 3) that's for @fabsx00

**Comment by clccc** [comment]
Thanks, I see
